# call_judge0_-211213-

目前問題是，當我call的時候，最後會出現這個(call docker)  
![image](https://user-images.githubusercontent.com/50321176/145726105-6e6baf39-a3fc-4d6b-a3c0-4752b4cf05aa.png)  
  
  
但是同樣的方法在postman是正常的。(call docker)  
![image](https://user-images.githubusercontent.com/50321176/145726134-b88a56cd-489f-4518-ab32-c1e7c1d12a3f.png)  
    

再當我去使用call api時(call Judge0 server)  
![image](https://user-images.githubusercontent.com/50321176/145726275-f2079f15-e900-4e3e-bf01-896e1c609564.png)  
雖然會有失敗的機率，但至少會出現正確的  


初步判斷問題：  
同步與非同步  
